[package]
name = "edx"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3.9", features = [
    "consoleapi",
    "wincon",
    "dxgi",
    "dxgitype",
    "dxgiformat",
    "d3d11",
    "d3dcompiler",
    "winuser",
    "memoryapi",
    "libloaderapi",
    "winerror"
] }